# Generated by Django 3.1.7 on 2021-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pen_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
