# Generated by Django 3.1.7 on 2021-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_content_pen_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='img2',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
