# Generated by Django 3.1.7 on 2021-05-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_content_img2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='img',
            new_name='img1',
        ),
    ]
